<?php

/**
 * MyTheme functions and definitions
 * Tailwind CLI version (NO CDN)
 */

if (!defined('ABSPATH')) {
  exit;
}


/* ======================================================
   Theme Setup
====================================================== */
function mytheme_setup()
{
  load_theme_textdomain('mytheme', get_template_directory() . '/languages');

  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');

  add_theme_support(
    'html5',
    array(
      'search-form',
      'comment-form',
      'comment-list',
      'gallery',
      'caption',
      'style',
      'script',
    )
  );

  add_theme_support(
    'custom-logo',
    array(
      'height' => 120,
      'width' => 320,
      'flex-height' => true,
      'flex-width' => true,
    )
  );

  register_nav_menus(
    array(
      'primary' => __('Primary Menu', 'mytheme'),
      'footer'  => __('Footer Menu', 'mytheme'),
    )
  );
}
add_action('after_setup_theme', 'mytheme_setup');



/* ======================================================
   Enqueue Assets (Tailwind compiled CSS)
====================================================== */
function mytheme_enqueue_assets()
{
  $theme_version = wp_get_theme()->get('Version');

  /**
   * Default WordPress style.css (theme info header only)
   */
  wp_enqueue_style(
    'mytheme-base',
    get_stylesheet_uri(),
    array(),
    $theme_version
  );

  /**
   * Tailwind compiled CSS (includes all custom styles and page-specific CSS)
   * This file is generated by:
   * npm run dev / npm run build
   */
  $tailwind_path = get_template_directory() . '/assets/css/style.css';

  wp_enqueue_style(
    'mytheme-tailwind',
    get_template_directory_uri() . '/assets/css/style.css',
    array('mytheme-base'),
    file_exists($tailwind_path) ? filemtime($tailwind_path) : $theme_version
  );

  /**
   * Main JS (bundled)
   */
  $bundle_js_path = get_template_directory() . '/assets/js/bundle.js';
  $main_js_path = get_template_directory() . '/assets/js/main.js';
  $script_uri = file_exists($bundle_js_path)
    ? get_template_directory_uri() . '/assets/js/bundle.js'
    : get_template_directory_uri() . '/assets/js/main.js';
  $script_ver = file_exists($bundle_js_path)
    ? filemtime($bundle_js_path)
    : (file_exists($main_js_path) ? filemtime($main_js_path) : $theme_version);

  wp_enqueue_script(
    'mytheme-main',
    $script_uri,
    array(),
    $script_ver,
    true
  );
}
add_action('wp_enqueue_scripts', 'mytheme_enqueue_assets');



/* ======================================================
  Helper: Image Asset Loader
====================================================== */
if (!function_exists('mytheme_img_asset')) {
  function mytheme_img_asset(string $path): string
  {
    $path = ltrim($path, '/');
    $dir = get_template_directory() . '/assets/img/';
    $uri = get_template_directory_uri() . '/assets/img/';

    $matches = glob($dir . $path . '.*');

    if ($matches && is_file($matches[0])) {
      return $uri . str_replace($dir, '', $matches[0]);
    }

    return get_template_directory_uri() . '/assets/img/hero-placeholder.svg';
  }
}

/* ======================================================
   Custom Walker for Dropdown Navigation (Tailwind)
====================================================== */
class Mytheme_Walker_Nav_Menu extends Walker_Nav_Menu
{
  /**
   * Start the element output.
   */
  public function start_el(&$output, $item, $depth = 0, $args = null, $id = 0)
  {
    $indent = ($depth) ? str_repeat("\t", $depth) : '';
    $classes = empty($item->classes) ? array() : (array) $item->classes;
    $classes[] = 'menu-item-' . $item->ID;

    // Add relative positioning for parent items
    if (in_array('menu-item-has-children', $classes)) {
      $classes[] = 'relative';
    }

    $class_names = join(' ', apply_filters('nav_menu_css_class', array_filter($classes), $item, $args, $depth));
    $class_names = $class_names ? ' class="' . esc_attr($class_names) . '"' : '';

    $id = apply_filters('nav_menu_item_id', 'menu-item-' . $item->ID, $item, $args, $depth);
    $id = $id ? ' id="' . esc_attr($id) . '"' : '';

    $output .= $indent . '<li' . $id . $class_names . '>';

    $atts = array();
    $atts['title']  = !empty($item->attr_title) ? $item->attr_title : '';
    $atts['target'] = !empty($item->target) ? $item->target : '';
    $atts['rel']    = !empty($item->xfn) ? $item->xfn : '';

    // Base link classes
    $link_classes = array();

    // If item has children, prevent default navigation
    if (in_array('menu-item-has-children', $classes)) {
      $atts['href'] = '#';
      $atts['aria-expanded'] = 'false';
      $atts['data-dropdown-toggle'] = 'true';
      
      // Parent link classes (desktop and mobile)
      if ($depth === 0) {
        $link_classes[] = 'flex items-center gap-2 lg:justify-between max-lg:w-full max-lg:justify-between';
      }
    } else {
      // Ensure absolute URL for submenu items
      $url = !empty($item->url) ? $item->url : '';
      // If URL is relative (starts with /), prepend home_url
      if (!empty($url) && substr($url, 0, 1) === '/' && substr($url, 0, 2) !== '//') {
        $url = home_url($url);
      }
      $atts['href'] = $url;
    }

    // Add Tailwind classes for submenu items
    if ($depth > 0) {
      $link_classes[] = 'block w-full px-3.5 py-2.5 rounded-lg text-[13px] font-semibold text-[rgba(43,43,43,0.8)] hover:bg-[rgba(110,186,56,0.08)] hover:text-[rgba(43,43,43,1)] transition-all duration-150';
    }

    if (!empty($link_classes)) {
      $atts['class'] = implode(' ', $link_classes);
    }

    $atts = apply_filters('nav_menu_link_attributes', $atts, $item, $args, $depth);

    $attributes = '';
    foreach ($atts as $attr => $value) {
      if (!empty($value)) {
        $value = ('href' === $attr) ? esc_url($value) : esc_attr($value);
        $attributes .= ' ' . $attr . '="' . $value . '"';
      }
    }

    $item_output = $args->before;
    $item_output .= '<a' . $attributes . '>';
    
    // Add dash prefix for submenu items
    $title_prefix = ($depth > 0) ? '— ' : '';
    $item_output .= $args->link_before . $title_prefix . apply_filters('the_title', $item->title, $item->ID) . $args->link_after;

    // Add plus icon for items with children
    if (in_array('menu-item-has-children', $classes)) {
      $item_output .= '<span class="dropdown-icon inline-flex items-center justify-center w-[10px] aspect-square" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
  <g id="plus" transform="translate(-1267 -92)">
    <rect id="長方形_657" data-name="長方形 657" width="10" height="2" transform="translate(1267 96)" fill="#6eba38"/>
    <rect id="長方形_657_のコピー" data-name="長方形 657 のコピー" width="2" height="10" transform="translate(1271 92)" fill="#6eba38"/>
  </g>
</svg>
</span>';
    }

    $item_output .= '</a>';
    $item_output .= $args->after;

    $output .= apply_filters('walker_nav_menu_start_el', $item_output, $item, $depth, $args);
  }

  /**
   * Start the sub-menu output.
   */
  public function start_lvl(&$output, $depth = 0, $args = null)
  {
    $indent = str_repeat("\t", $depth);
    // Tailwind classes for dropdown: hidden by default, positioned absolutely on desktop, static on mobile
    $classes = 'sub-menu hidden lg:absolute lg:top-[calc(100%+12px)] lg:left-0 lg:min-w-[200px] lg:bg-white lg:shadow-[0_10px_30px_rgba(0,0,0,0.15)] lg:border lg:border-black/[0.08] lg:p-2 lg:z-[1000] max-lg:static max-lg:mt-2 max-lg:pl-4 max-lg:border-l-2 max-lg:border-[rgba(110,186,56,0.3)] list-none m-0 p-0';
    $output .= "\n$indent<ul class=\"$classes\">\n";
  }
}

/* ======================================================
   Footer Walker - No Dropdown, Show All Items
====================================================== */
class Mytheme_Walker_Footer_Nav_Menu extends Walker_Nav_Menu
{
  /**
   * Start the element output.
   */
  public function start_el(&$output, $item, $depth = 0, $args = null, $id = 0)
  {
    $indent = ($depth) ? str_repeat("\t", $depth) : '';
    $classes = empty($item->classes) ? array() : (array) $item->classes;
    $classes[] = 'menu-item-' . $item->ID;

    $class_names = join(' ', apply_filters('nav_menu_css_class', array_filter($classes), $item, $args, $depth));
    $class_names = $class_names ? ' class="' . esc_attr($class_names) . '"' : '';

    $id = apply_filters('nav_menu_item_id', 'menu-item-' . $item->ID, $item, $args, $depth);
    $id = $id ? ' id="' . esc_attr($id) . '"' : '';

    $output .= $indent . '<li' . $id . $class_names . '>';

    $atts = array();
    $atts['title']  = !empty($item->attr_title) ? $item->attr_title : '';
    $atts['target'] = !empty($item->target) ? $item->target : '';
    $atts['rel']    = !empty($item->xfn) ? $item->xfn : '';

    // All items are clickable in footer
    $url = !empty($item->url) ? $item->url : '';
    // If URL is relative (starts with /), prepend home_url
    if (!empty($url) && substr($url, 0, 1) === '/' && substr($url, 0, 2) !== '//') {
      $url = home_url($url);
    }
    $atts['href'] = $url;

    $atts = apply_filters('nav_menu_link_attributes', $atts, $item, $args, $depth);

    $attributes = '';
    foreach ($atts as $attr => $value) {
      if (!empty($value)) {
        $value = ('href' === $attr) ? esc_url($value) : esc_attr($value);
        $attributes .= ' ' . $attr . '="' . $value . '"';
      }
    }

    $item_output = $args->before;
    $item_output .= '<a' . $attributes . '>';
    
    // Add dash prefix for submenu items
    $title_prefix = ($depth > 0) ? '— ' : '';
    $item_output .= $args->link_before . $title_prefix . apply_filters('the_title', $item->title, $item->ID) . $args->link_after;

    $item_output .= '</a>';
    $item_output .= $args->after;

    $output .= apply_filters('walker_nav_menu_start_el', $item_output, $item, $depth, $args);
  }

  /**
   * Start the sub-menu output - No special classes, just a simple list
   */
  public function start_lvl(&$output, $depth = 0, $args = null)
  {
    $indent = str_repeat("\t", $depth);
    $output .= "\n$indent<ul class=\"sub-menu\">\n";
  }
}

/* ======================================================
   Widgets
====================================================== */
function mytheme_widgets_init()
{
  register_sidebar(
    array(
      'name'          => __('Sidebar', 'mytheme'),
      'id'            => 'sidebar-1',
      'description'   => __('Add widgets here.', 'mytheme'),
      'before_widget' => '<section id="%1$s" class="widget %2$s">',
      'after_widget'  => '</section>',
      'before_title'  => '<h2 class="widget__title">',
      'after_title'   => '</h2>',
    )
  );
}
add_action('widgets_init', 'mytheme_widgets_init');
