<?php

/**
 * MyTheme functions and definitions
 * Tailwind CLI version (NO CDN)
 */

if (!defined('ABSPATH')) {
  exit;
}


/* ======================================================
   Theme Setup
====================================================== */
function mytheme_setup()
{
  load_theme_textdomain('mytheme', get_template_directory() . '/languages');

  add_theme_support('title-tag');
  add_theme_support('post-thumbnails');

  add_theme_support(
    'html5',
    array(
      'search-form',
      'comment-form',
      'comment-list',
      'gallery',
      'caption',
      'style',
      'script',
    )
  );

  add_theme_support(
    'custom-logo',
    array(
      'height' => 120,
      'width' => 320,
      'flex-height' => true,
      'flex-width' => true,
    )
  );

  register_nav_menus(
    array(
      'primary' => __('Primary Menu', 'mytheme'),
      'footer'  => __('Footer Menu', 'mytheme'),
    )
  );
}
add_action('after_setup_theme', 'mytheme_setup');



/* ======================================================
   Enqueue Assets (Tailwind compiled CSS)
====================================================== */
function mytheme_enqueue_assets()
{
  $theme_version = wp_get_theme()->get('Version');

  /**
   * Default WordPress style.css (theme info header only)
   */
  wp_enqueue_style(
    'mytheme-base',
    get_stylesheet_uri(),
    array(),
    $theme_version
  );

  /**
   * Tailwind compiled CSS (includes all custom styles and page-specific CSS)
   * This file is generated by:
   * npm run dev / npm run build
   */
  $tailwind_path = get_template_directory() . '/assets/css/style.css';

  wp_enqueue_style(
    'mytheme-tailwind',
    get_template_directory_uri() . '/assets/css/style.css',
    array('mytheme-base'),
    file_exists($tailwind_path) ? filemtime($tailwind_path) : $theme_version
  );

  /**
   * Main JS
   */
  $main_js_path = get_template_directory() . '/assets/js/main.js';

  wp_enqueue_script(
    'mytheme-main',
    get_template_directory_uri() . '/assets/js/main.js',
    array(),
    file_exists($main_js_path) ? filemtime($main_js_path) : $theme_version,
    true
  );
}
add_action('wp_enqueue_scripts', 'mytheme_enqueue_assets');



/* ======================================================
   Helper: Top Image Asset Loader
====================================================== */
if (!function_exists('mytheme_top_asset')) {
  function mytheme_top_asset(string $base): string
  {
    $dir = get_template_directory() . '/assets/img/top/';
    $uri = get_template_directory_uri() . '/assets/img/top/';

    $matches = glob($dir . $base . '.*');

    if ($matches && is_file($matches[0])) {
      return $uri . basename($matches[0]);
    }

    return get_template_directory_uri() . '/assets/img/hero-placeholder.svg';
  }
}



/* ======================================================
   Widgets
====================================================== */
function mytheme_widgets_init()
{
  register_sidebar(
    array(
      'name'          => __('Sidebar', 'mytheme'),
      'id'            => 'sidebar-1',
      'description'   => __('Add widgets here.', 'mytheme'),
      'before_widget' => '<section id="%1$s" class="widget %2$s">',
      'after_widget'  => '</section>',
      'before_title'  => '<h2 class="widget__title">',
      'after_title'   => '</h2>',
    )
  );
}
add_action('widgets_init', 'mytheme_widgets_init');
